const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

// JWT
const JWT = {
  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_MS: 'JWT_ACCESS_TOKEN_EXPIRATION_MS',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_MS: 'JWT_REFRESH_TOKEN_EXPIRATION_MS',
} as const;

const NOTIFICATION = {
  NOTIFICATION_SERVER_EXCEPTION: 'NOTIFICATION_SERVER_EXCEPTION',
} as const;

export const ENV_KEY = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  ...JWT,
  ...DATABASE,
  ...NOTIFICATION,
} as const;
